name: SearchChestshop2
version: ${project.version}
main: com.over2craft.searchchestshop2.SearchChestshop
api-version: 1.16
depend: [ChestShop, SmartInvs]

commands:
  shopsearch2:
    description: Search an item among shop signs
    permission: over2craft.shopsearch2.use
    aliases: []

permissions:
  over2craft.shopsearch2.use:
    description: Allow shopsearch2
    default: true
  over2craft.shopsearch2.reload:
    description: Allow shopsearch configuration reload /shopsearch2 $reload
    default: op